<?php
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
if (!function_exists('getSiteUrl')) {
    /**
     * Return the base site URL.
     *
     * @return string
     */
    function getSiteUrl()
    {
        return config('app.url');
    }
}
if (!function_exists('formatDate')) {
    /**
     * Format a given date into a readable format.
     *
     * @param string $date
     * @return string
     */
    function formatDate($date)
    {
        return \Carbon\Carbon::parse($date)->format('d-m-Y');
    }
}

if (!function_exists('getBreadCrumData')) {
    /**
     * Format a given date into a readable format.
     *
     * @param string $date
     * @return string
     */
    function getBreadCrumData()
    {


        $route =  Request::route();
        $menuTable = (strpos($route->uri(), 'society') === 0) ? 'society_menus' : 'menus';
        //dump( $route->uri() );

        $segment = Request::segments();
        $lastData = end($segment);
        if($lastData =='edit'){
            $newUrl = implode('/', array_slice($segment, 0, -2));
        } else if($lastData =='create'){
            $newUrl = implode('/', array_slice($segment, 0, -1));

        } else {
            $newUrl = $route->uri;
        }

        $menu = DB::table($menuTable)->where('url', $newUrl)->first();
        $menuId = $menu->id;

        $hierarchy = [];
        if ( request()->isMethod('get')  && str_contains(request()->path(), 'edit')) {
            $menu = (object) array(
                "id" => null,
                'name' => "edit",
                "page_heading" =>  $menu->page_heading,
                'url' => null
            );
            $hierarchy[] = $menu;
        }
        while ($menuId) {
            $menu = DB::table($menuTable)->where('id', $menuId)->first();
            if ($menu) {
                $hierarchy[] = $menu;
                $menuId = $menu->parent_id; // Move to the parent ID
            } else {
                break;
            }
        }

        return $hierarchy;
    }
}


if (!function_exists('getIconList')) {
    /**
     * Get a list of available FontAwesome icons.
     *
     * @return array
     */
    function getIconList()
    {
        return [
            'fa-align-left' => '&#xf036; fa-align-left',
            'fa-align-right' => '&#xf038; fa-align-right',
            'fa-amazon' => '&#xf270; fa-amazon',
            'fa-ambulance' => '&#xf0f9; fa-ambulance',
            'fa-anchor' => '&#xf13d; fa-anchor',
            'fa-android' => '&#xf17b; fa-android',
            'fa-angellist' => '&#xf209; fa-angellist',
            'fa-angle-double-down' => '&#xf103; fa-angle-double-down',
            'fa-angle-double-left' => '&#xf100; fa-angle-double-left',
            'fa-angle-double-right' => '&#xf101; fa-angle-double-right',
            'fa-angle-double-up' => '&#xf102; fa-angle-double-up',

            'fa-angle-left' => '&#xf104; fa-angle-left',
            'fa-angle-right' => '&#xf105; fa-angle-right',
            'fa-angle-up' => '&#xf106; fa-angle-up',
            'fa-apple' => '&#xf179; fa-apple',
            'fa-archive' => '&#xf187; fa-archive',
            'fa-area-chart' => '&#xf1fe; fa-area-chart',
            'fa-arrow-circle-down' => '&#xf0ab; fa-arrow-circle-down',
            'fa-arrow-circle-left' => '&#xf0a8; fa-arrow-circle-left',
            'fa-arrow-circle-o-down' => '&#xf01a; fa-arrow-circle-o-down',
            'fa-arrow-circle-o-left' => '&#xf190; fa-arrow-circle-o-left',
            'fa-arrow-circle-o-right' => '&#xf18e; fa-arrow-circle-o-right',
            'fa-arrow-circle-o-up' => '&#xf01b; fa-arrow-circle-o-up',
            'fa-arrow-circle-right' => '&#xf0a9; fa-arrow-circle-right',
            'fa-arrow-circle-up' => '&#xf0aa; fa-arrow-circle-up',
            'fa-arrow-down' => '&#xf063; fa-arrow-down',
            'fa-arrow-left' => '&#xf060; fa-arrow-left',
            'fa-arrow-right' => '&#xf061; fa-arrow-right',
            'fa-arrow-up' => '&#xf062; fa-arrow-up',
            'fa-arrows' => '&#xf047; fa-arrows',
            'fa-arrows-alt' => '&#xf0b2; fa-arrows-alt',
            'fa-arrows-h' => '&#xf07e; fa-arrows-h',
            'fa-arrows-v' => '&#xf07d; fa-arrows-v',
            'fa-asterisk' => '&#xf069; fa-asterisk',
            'fa-at' => '&#xf1fa; fa-at',
            'fa-automobile' => '&#xf1b9; fa-automobile',
            'fa-backward' => '&#xf04a; fa-backward',
            'fa-balance-scale' => '&#xf24e; fa-balance-scale',
            'fa-ban' => '&#xf05e; fa-ban',
            'fa-bank' => '&#xf19c; fa-bank',
            'fa-bar-chart' => '&#xf080; fa-bar-chart',
            'fa-bar-chart-o' => '&#xf080; fa-bar-chart-o',

            'fa-battery-full' => '&#xf240; fa-battery-full',
            'fa-beer' => '&#xf0fc; fa-beer',
            'fa-behance' => '&#xf1b4; fa-behance',
            'fa-behance-square' => '&#xf1b5; fa-behance-square',
            'fa-bell' => '&#xf0f3; fa-bell',
            'fa-bell-o' => '&#xf0a2; fa-bell-o',
            'fa-bell-slash' => '&#xf1f6; fa-bell-slash',
            'fa-bell-slash-o' => '&#xf1f7; fa-bell-slash-o',
            'fa-bicycle' => '&#xf206; fa-bicycle',
            'fa-binoculars' => '&#xf1e5; fa-binoculars',
            'fa-birthday-cake' => '&#xf1fd; fa-birthday-cake',
            'fa-bitbucket' => '&#xf171; fa-bitbucket',
            'fa-bitbucket-square' => '&#xf172; fa-bitbucket-square',
            'fa-bitcoin' => '&#xf15a; fa-bitcoin',
            'fa-black-tie' => '&#xf27e; fa-black-tie',
            'fa-bold' => '&#xf032; fa-bold',
            'fa-bolt' => '&#xf0e7; fa-bolt',
            'fa-bomb' => '&#xf1e2; fa-bomb',
            'fa-book' => '&#xf02d; fa-book',
            'fa-bookmark' => '&#xf02e; fa-bookmark',
            'fa-bookmark-o' => '&#xf097; fa-bookmark-o',
            'fa-briefcase' => '&#xf0b1; fa-briefcase',
            'fa-btc' => '&#xf15a; fa-btc',
            'fa-bug' => '&#xf188; fa-bug',
            'fa-building' => '&#xf1ad; fa-building',
            'fa-building-o' => '&#xf0f7; fa-building-o',
            'fa-bullhorn' => '&#xf0a1; fa-bullhorn',
            'fa-bullseye' => '&#xf140; fa-bullseye',
            'fa-bus' => '&#xf207; fa-bus',
            'fa-cab' => '&#xf1ba; fa-cab',
            'fa-calendar' => '&#xf073; fa-calendar',
            'fa-camera' => '&#xf030; fa-camera',
            'fa-car' => '&#xf1b9; fa-car',
            'fa-caret-up' => '&#xf0d8; fa-caret-up',
            'fa-cart-plus' => '&#xf217; fa-cart-plus',
            'fa-cc' => '&#xf20a; fa-cc',
            'fa-cc-amex' => '&#xf1f3; fa-cc-amex',
            'fa-cc-jcb' => '&#xf24b; fa-cc-jcb',
            'fa-cc-paypal' => '&#xf1f4; fa-cc-paypal',
            'fa-cc-stripe' => '&#xf1f5; fa-cc-stripe',
            'fa-cc-visa' => '&#xf1f0; fa-cc-visa',
            'fa-chain' => '&#xf0c1; fa-chain',
            'fa-check' => '&#xf00c; fa-check',
            'fa-chevron-left' => '&#xf053; fa-chevron-left',
            'fa-chevron-right' => '&#xf054; fa-chevron-right',
            'fa-chevron-up' => '&#xf077; fa-chevron-up',
            'fa-child' => '&#xf1ae; fa-child',
            'fa-chrome' => '&#xf268; fa-chrome',
            'fa-circle' => '&#xf111; fa-circle',
            'fa-circle-o' => '&#xf10c; fa-circle-o',
            'fa-circle-o-notch' => '&#xf1ce; fa-circle-o-notch',
            'fa-circle-thin' => '&#xf1db; fa-circle-thin',
            'fa-clipboard' => '&#xf0ea; fa-clipboard',
            'fa-clock-o' => '&#xf017; fa-clock-o',
            'fa-clone' => '&#xf24d; fa-clone',
            'fa-close' => '&#xf00d; fa-close',
            'fa-cloud' => '&#xf0c2; fa-cloud',
            'fa-cloud-download' => '&#xf0ed; fa-cloud-download',
            'fa-cloud-upload' => '&#xf0ee; fa-cloud-upload',
            'fa-cny' => '&#xf157; fa-cny',
            'fa-code' => '&#xf121; fa-code',
            'fa-code-fork' => '&#xf126; fa-code-fork',
            'fa-codepen' => '&#xf1cb; fa-codepen',
            'fa-coffee' => '&#xf0f4; fa-coffee',
            'fa-cog' => '&#xf013; fa-cog',
            'fa-cogs' => '&#xf085; fa-cogs',
            'fa-columns' => '&#xf0db; fa-columns',
            'fa-comment' => '&#xf075; fa-comment',
            'fa-comment-o' => '&#xf0e5; fa-comment-o',
            'fa-commenting' => '&#xf27a; fa-commenting',
            'fa-commenting-o' => '&#xf27b; fa-commenting-o',
            'fa-comments' => '&#xf086; fa-comments',
            'fa-comments-o' => '&#xf0e6; fa-comments-o',
            'fa-compass' => '&#xf14e; fa-compass',
            'fa-compress' => '&#xf066; fa-compress',
            'fa-connectdevelop' => '&#xf20e; fa-connectdevelop',
            'fa-contao' => '&#xf26d; fa-contao',
            'fa-copy' => '&#xf0c5; fa-copy',
            'fa-copyright' => '&#xf1f9; fa-copyright',
            'fa-creative-commons' => '&#xf25e; fa-creative-commons',
            'fa-credit-card' => '&#xf09d; fa-credit-card',
            'fa-crop' => '&#xf125; fa-crop',
            'fa-crosshairs' => '&#xf05b; fa-crosshairs',
            'fa-css3' => '&#xf13c; fa-css3',
            'fa-cube' => '&#xf1b2; fa-cube',
            'fa-cubes' => '&#xf1b3; fa-cubes',
            'fa-cut' => '&#xf0c4; fa-cut',
            'fa-cutlery' => '&#xf0f5; fa-cutlery',
            'fa-dashboard' => '&#xf0e4; fa-dashboard',
            'fa-dashcube' => '&#xf210; fa-dashcube',
            'fa-database' => '&#xf1c0; fa-database',
            'fa-dedent' => '&#xf03b; fa-dedent',
            'fa-delicious' => '&#xf1a5; fa-delicious',
            'fa-desktop' => '&#xf108; fa-desktop',
            'fa-deviantart' => '&#xf1bd; fa-deviantart',
            'fa-diamond' => '&#xf219; fa-diamond',
            'fa-digg' => '&#xf1a6; fa-digg',
            'fa-dollar' => '&#xf155; fa-dollar',
            'fa-download' => '&#xf019; fa-download',
            'fa-dribbble' => '&#xf17d; fa-dribbble',
            'fa-dropbox' => '&#xf16b; fa-dropbox',
            'fa-drupal' => '&#xf1a9; fa-drupal',
            'fa-edit' => '&#xf044; fa-edit',
            'fa-eject' => '&#xf052; fa-eject',
            'fa-ellipsis-h' => '&#xf141; fa-ellipsis-h',
            'fa-ellipsis-v' => '&#xf142; fa-ellipsis-v',
            'fa-empire' => '&#xf1d1; fa-empire',
            'fa-envelope' => '&#xf0e0; fa-envelope',
            'fa-envelope-o' => '&#xf003; fa-envelope-o',
            'fa-eur' => '&#xf153; fa-eur',
            'fa-euro' => '&#xf153; fa-euro',
            'fa-exchange' => '&#xf0ec; fa-exchange',
            'fa-exclamation' => '&#xf12a; fa-exclamation',
            'fa-exclamation-circle' => '&#xf06a; fa-exclamation-circle',
            'fa-exclamation-triangle' => '&#xf071; fa-exclamation-triangle',
            'fa-expand' => '&#xf065; fa-expand',
            'fa-expeditedssl' => '&#xf23e; fa-expeditedssl',
            'fa-external-link' => '&#xf08e; fa-external-link',
            'fa-external-link-square' => '&#xf14c; fa-external-link-square',
            'fa-eye' => '&#xf06e; fa-eye',
            'fa-eye-slash' => '&#xf070; fa-eye-slash',
            'fa-eyedropper' => '&#xf1fb; fa-eyedropper',
            'fa-facebook' => '&#xf09a; fa-facebook',
            'fa-facebook-f' => '&#xf09a; fa-facebook-f',
            'fa-facebook-official' => '&#xf230; fa-facebook-official',
            'fa-facebook-square' => '&#xf082; fa-facebook-square',
            'fa-fast-backward' => '&#xf049; fa-fast-backward',
            'fa-fast-forward' => '&#xf050; fa-fast-forward',
            'fa-fax' => '&#xf1ac; fa-fax',
            'fa-feed' => '&#xf09e; fa-feed',
            'fa-female' => '&#xf182; fa-female',
            'fa-fighter-jet' => '&#xf0fb; fa-fighter-jet',
            'fa-file' => '&#xf15b; fa-file',
            'fa-file-archive-o' => '&#xf1c6; fa-file-archive-o',
            'fa-file-audio-o' => '&#xf1c7; fa-file-audio-o',
            'fa-file-code-o' => '&#xf1c9; fa-file-code-o',
            'fa-file-excel-o' => '&#xf1c3; fa-file-excel-o',
            'fa-file-image-o' => '&#xf1c5; fa-file-image-o',
            'fa-file-movie-o' => '&#xf1c8; fa-file-movie-o',
            'fa-file-o' => '&#xf016; fa-file-o',
            'fa-file-pdf-o' => '&#xf1c1; fa-file-pdf-o',
            'fa-file-photo-o' => '&#xf1c5; fa-file-photo-o',
            'fa-file-picture-o' => '&#xf1c5; fa-file-picture-o',
            'fa-file-powerpoint-o' => '&#xf1c4; fa-file-powerpoint-o',
            'fa-file-sound-o' => '&#xf1c7; fa-file-sound-o',
            'fa-file-text' => '&#xf15c; fa-file-text',
            'fa-file-text-o' => '&#xf0f6; fa-file-text-o',
            'fa-file-video-o' => '&#xf1c8; fa-file-video-o',
            'fa-file-word-o' => '&#xf1c2; fa-file-word-o',
            'fa-file-zip-o' => '&#xf1c6; fa-file-zip-o',
            'fa-files-o' => '&#xf0c5; fa-files-o',
            'fa-film' => '&#xf008; fa-film',
            'fa-filter' => '&#xf0b0; fa-filter',
            'fa-fire' => '&#xf06d; fa-fire',
            'fa-fire-extinguisher' => '&#xf134; fa-fire-extinguisher',
            'fa-firefox' => '&#xf269; fa-firefox',
            'fa-flag' => '&#xf024; fa-flag',
            'fa-flag-checkered' => '&#xf11e; fa-flag-checkered',
            'fa-flag-o' => '&#xf11d; fa-flag-o',
            'fa-flash' => '&#xf0e7; fa-flash',
            'fa-flask' => '&#xf0c3; fa-flask',
            'fa-flickr' => '&#xf16e; fa-flickr',
            'fa-floppy-o' => '&#xf0c7; fa-floppy-o',
            'fa-folder' => '&#xf07b; fa-folder',
            'fa-folder-o' => '&#xf114; fa-folder-o',
            'fa-folder-open' => '&#xf07c; fa-folder-open',
            'fa-folder-open-o' => '&#xf115; fa-folder-open-o',
            'fa-font' => '&#xf031; fa-font',
            'fa-fonticons' => '&#xf280; fa-fonticons',
            'fa-forumbee' => '&#xf211; fa-forumbee',
            'fa-forward' => '&#xf04e; fa-forward',
            'fa-foursquare' => '&#xf180; fa-foursquare',
            'fa-frown-o' => '&#xf119; fa-frown-o',
            'fa-futbol-o' => '&#xf1e3; fa-futbol-o',
            'fa-gamepad' => '&#xf11b; fa-gamepad',
            'fa-gavel' => '&#xf0e3; fa-gavel',
            'fa-gbp' => '&#xf154; fa-gbp',
            'fa-ge' => '&#xf1d1; fa-ge',
            'fa-gear' => '&#xf013; fa-gear',
            'fa-gears' => '&#xf085; fa-gears',
            'fa-genderless' => '&#xf22d; fa-genderless',
            'fa-get-pocket' => '&#xf265; fa-get-pocket',
            'fa-gg' => '&#xf260; fa-gg',
            'fa-gg-circle' => '&#xf261; fa-gg-circle',
            'fa-gift' => '&#xf06b; fa-gift',
            'fa-git' => '&#xf1d3; fa-git',
            'fa-git-square' => '&#xf1d2; fa-git-square',
            'fa-github' => '&#xf09b; fa-github',
            'fa-github-alt' => '&#xf113; fa-github-alt',
            'fa-github-square' => '&#xf092; fa-github-square',
            'fa-gittip' => '&#xf184; fa-gittip',
            'fa-glass' => '&#xf000; fa-glass',
            'fa-globe' => '&#xf0ac; fa-globe',
            'fa-google' => '&#xf1a0; fa-google',
            'fa-google-plus' => '&#xf0d5; fa-google-plus',
            'fa-google-plus-square' => '&#xf0d4; fa-google-plus-square',
            'fa-google-wallet' => '&#xf1ee; fa-google-wallet',
            'fa-graduation-cap' => '&#xf19d; fa-graduation-cap',
            'fa-gratipay' => '&#xf184; fa-gratipay',
            'fa-group' => '&#xf0c0; fa-group',
            'fa-h-square' => '&#xf0fd; fa-h-square',
            'fa-hacker-news' => '&#xf1d4; fa-hacker-news',
            'fa-hand-grab-o' => '&#xf255; fa-hand-grab-o',
            'fa-hand-lizard-o' => '&#xf258; fa-hand-lizard-o',
            'fa-hand-o-down' => '&#xf0a7; fa-hand-o-down',
            'fa-hand-o-left' => '&#xf0a5; fa-hand-o-left',
            'fa-hand-o-right' => '&#xf0a4; fa-hand-o-right',
            'fa-hand-o-up' => '&#xf0a6; fa-hand-o-up',
            'fa-hand-paper-o' => '&#xf256; fa-hand-paper-o',
            'fa-hand-peace-o' => '&#xf25b; fa-hand-peace-o',
            'fa-hand-pointer-o' => '&#xf25a; fa-hand-pointer-o',
            'fa-hand-rock-o' => '&#xf255; fa-hand-rock-o',
            'fa-hand-scissors-o' => '&#xf257; fa-hand-scissors-o',
            'fa-hand-spock-o' => '&#xf259; fa-hand-spock-o',
            'fa-hand-stop-o' => '&#xf256; fa-hand-stop-o',
            'fa-hdd-o' => '&#xf0a0; fa-hdd-o',
            'fa-header' => '&#xf1dc; fa-header',
            'fa-headphones' => '&#xf025; fa-headphones',
            'fa-heart' => '&#xf004; fa-heart',
            'fa-heart-o' => '&#xf08a; fa-heart-o',
            'fa-heartbeat' => '&#xf21e; fa-heartbeat',
            'fa-history' => '&#xf1da; fa-history',
            'fa-home' => '&#xf015; fa-home',
            'fa-hospital-o' => '&#xf0f8; fa-hospital-o',
            'fa-hotel' => '&#xf236; fa-hotel',
            'fa-hourglass' => '&#xf254; fa-hourglass',
            'fa-hourglass-1' => '&#xf251; fa-hourglass-1',
            'fa-hourglass-2' => '&#xf252; fa-hourglass-2',
            'fa-hourglass-3' => '&#xf253; fa-hourglass-3',
            'fa-hourglass-end' => '&#xf253; fa-hourglass-end',
            'fa-hourglass-half' => '&#xf252; fa-hourglass-half',
            'fa-hourglass-o' => '&#xf250; fa-hourglass-o',
            'fa-hourglass-start' => '&#xf251; fa-hourglass-start',
            'fa-houzz' => '&#xf27c; fa-houzz',
            'fa-html5' => '&#xf13b; fa-html5',
            'fa-i-cursor' => '&#xf246; fa-i-cursor',
            'fa-ils' => '&#xf20b; fa-ils',
            'fa-image' => '&#xf03e; fa-image',
            'fa-inbox' => '&#xf01c; fa-inbox',
            'fa-indent' => '&#xf03c; fa-indent',
            'fa-industry' => '&#xf275; fa-industry',
            'fa-info' => '&#xf129; fa-info',
            'fa-info-circle' => '&#xf05a; fa-info-circle',
            'fa-inr' => '&#xf156; fa-inr',
            'fa-instagram' => '&#xf16d; fa-instagram',
            'fa-institution' => '&#xf19c; fa-institution',
            'fa-internet-explorer' => '&#xf26b; fa-internet-explorer',
            'fa-intersex' => '&#xf224; fa-intersex',
            'fa-ioxhost' => '&#xf208; fa-ioxhost',
            'fa-italic' => '&#xf033; fa-italic',
            'fa-joomla' => '&#xf1aa; fa-joomla',
            'fa-jpy' => '&#xf157; fa-jpy',
            'fa-jsfiddle' => '&#xf1cc; fa-jsfiddle',
            'fa-key' => '&#xf084; fa-key',
            'fa-keyboard-o' => '&#xf11c; fa-keyboard-o',
            'fa-krw' => '&#xf159; fa-krw',
            'fa-language' => '&#xf1ab; fa-language',
            'fa-laptop' => '&#xf109; fa-laptop',
            'fa-lastfm' => '&#xf202; fa-lastfm',
            'fa-lastfm-square' => '&#xf203; fa-lastfm-square',
            'fa-leaf' => '&#xf06c; fa-leaf',
            'fa-leanpub' => '&#xf212; fa-leanpub',
            'fa-legal' => '&#xf0e3; fa-legal',
            'fa-lemon-o' => '&#xf094; fa-lemon-o',
            'fa-level-down' => '&#xf149; fa-level-down',
            'fa-level-up' => '&#xf148; fa-level-up',
            'fa-life-bouy' => '&#xf1cd; fa-life-bouy',
            'fa-life-buoy' => '&#xf1cd; fa-life-buoy',
            'fa-life-ring' => '&#xf1cd; fa-life-ring',
            'fa-life-saver' => '&#xf1cd; fa-life-saver',
            'fa-lightbulb-o' => '&#xf0eb; fa-lightbulb-o',
            'fa-line-chart' => '&#xf201; fa-line-chart',
            'fa-link' => '&#xf0c1; fa-link',
            'fa-linkedin' => '&#xf0e1; fa-linkedin',
            'fa-linkedin-square' => '&#xf08c; fa-linkedin-square',
            'fa-linux' => '&#xf17c; fa-linux',
            'fa-list' => '&#xf03a; fa-list',
            'fa-list-alt' => '&#xf022; fa-list-alt',
            'fa-list-ol' => '&#xf0cb; fa-list-ol',
            'fa-list-ul' => '&#xf0ca; fa-list-ul',
            'fa-location-arrow' => '&#xf124; fa-location-arrow',
            'fa-lock' => '&#xf023; fa-lock',
            'fa-long-arrow-down' => '&#xf175; fa-long-arrow-down',
            'fa-long-arrow-left' => '&#xf177; fa-long-arrow-left',
            'fa-long-arrow-right' => '&#xf178; fa-long-arrow-right',
            'fa-long-arrow-up' => '&#xf176; fa-long-arrow-up',
            'fa-magic' => '&#xf0d0; fa-magic',
            'fa-magnet' => '&#xf076; fa-magnet',

            'fa-mars-stroke-v' => '&#xf22a; fa-mars-stroke-v',
            'fa-maxcdn' => '&#xf136; fa-maxcdn',
            'fa-meanpath' => '&#xf20c; fa-meanpath',
            'fa-medium' => '&#xf23a; fa-medium',
            'fa-medkit' => '&#xf0fa; fa-medkit',
            'fa-meh-o' => '&#xf11a; fa-meh-o',
            'fa-mercury' => '&#xf223; fa-mercury',
            'fa-microphone' => '&#xf130; fa-microphone',
            'fa-mobile' => '&#xf10b; fa-mobile',
            'fa-motorcycle' => '&#xf21c; fa-motorcycle',
            'fa-mouse-pointer' => '&#xf245; fa-mouse-pointer',
            'fa-music' => '&#xf001; fa-music',
            'fa-navicon' => '&#xf0c9; fa-navicon',
            'fa-neuter' => '&#xf22c; fa-neuter',
            'fa-newspaper-o' => '&#xf1ea; fa-newspaper-o',
            'fa-opencart' => '&#xf23d; fa-opencart',
            'fa-openid' => '&#xf19b; fa-openid',
            'fa-opera' => '&#xf26a; fa-opera',
            'fa-outdent' => '&#xf03b; fa-outdent',
            'fa-pagelines' => '&#xf18c; fa-pagelines',
            'fa-paper-plane-o' => '&#xf1d9; fa-paper-plane-o',
            'fa-paperclip' => '&#xf0c6; fa-paperclip',
            'fa-paragraph' => '&#xf1dd; fa-paragraph',
            'fa-paste' => '&#xf0ea; fa-paste',
            'fa-pause' => '&#xf04c; fa-pause',
            'fa-paw' => '&#xf1b0; fa-paw',
            'fa-paypal' => '&#xf1ed; fa-paypal',
            'fa-pencil' => '&#xf040; fa-pencil',
            'fa-pencil-square-o' => '&#xf044; fa-pencil-square-o',
            'fa-phone' => '&#xf095; fa-phone',
            'fa-photo' => '&#xf03e; fa-photo',
            'fa-picture-o' => '&#xf03e; fa-picture-o',
            'fa-pie-chart' => '&#xf200; fa-pie-chart',
            'fa-pied-piper' => '&#xf1a7; fa-pied-piper',
            'fa-pied-piper-alt' => '&#xf1a8; fa-pied-piper-alt',
            'fa-pinterest' => '&#xf0d2; fa-pinterest',
            'fa-pinterest-p' => '&#xf231; fa-pinterest-p',
            'fa-pinterest-square' => '&#xf0d3; fa-pinterest-square',
            'fa-plane' => '&#xf072; fa-plane',
            'fa-play' => '&#xf04b; fa-play',
            'fa-play-circle' => '&#xf144; fa-play-circle',
            'fa-play-circle-o' => '&#xf01d; fa-play-circle-o',
            'fa-plug' => '&#xf1e6; fa-plug',
            'fa-plus' => '&#xf067; fa-plus',
            'fa-plus-circle' => '&#xf055; fa-plus-circle',
            'fa-plus-square' => '&#xf0fe; fa-plus-square',
            'fa-plus-square-o' => '&#xf196; fa-plus-square-o',
            'fa-power-off' => '&#xf011; fa-power-off',
            'fa-print' => '&#xf02f; fa-print',
            'fa-puzzle-piece' => '&#xf12e; fa-puzzle-piece',
            'fa-qq' => '&#xf1d6; fa-qq',
            'fa-qrcode' => '&#xf029; fa-qrcode',
            'fa-question' => '&#xf128; fa-question',
            'fa-question-circle' => '&#xf059; fa-question-circle',
            'fa-quote-left' => '&#xf10d; fa-quote-left',
            'fa-quote-right' => '&#xf10e; fa-quote-right',
            'fa-ra' => '&#xf1d0; fa-ra',
            'fa-random' => '&#xf074; fa-random',
            'fa-rebel' => '&#xf1d0; fa-rebel',
            'fa-recycle' => '&#xf1b8; fa-recycle',
            'fa-reddit' => '&#xf1a1; fa-reddit',
            'fa-reddit-square' => '&#xf1a2; fa-reddit-square',
            'fa-refresh' => '&#xf021; fa-refresh',
            'fa-registered' => '&#xf25d; fa-registered',
            'fa-remove' => '&#xf00d; fa-remove',
            'fa-renren' => '&#xf18b; fa-renren',
            'fa-reorder' => '&#xf0c9; fa-reorder',
            'fa-repeat' => '&#xf01e; fa-repeat',
            'fa-reply' => '&#xf112; fa-reply',
            'fa-reply-all' => '&#xf122; fa-reply-all',
            'fa-retweet' => '&#xf079; fa-retweet',
            'fa-rmb' => '&#xf157; fa-rmb',
            'fa-road' => '&#xf018; fa-road',
            'fa-rocket' => '&#xf135; fa-rocket',
            'fa-rotate-left' => '&#xf0e2; fa-rotate-left',
            'fa-rotate-right' => '&#xf01e; fa-rotate-right',
            'fa-rouble' => '&#xf158; fa-rouble',
            'fa-rss' => '&#xf09e; fa-rss',
            'fa-rss-square' => '&#xf143; fa-rss-square',
            'fa-rub' => '&#xf158; fa-rub',
            'fa-ruble' => '&#xf158; fa-ruble',
            'fa-rupee' => '&#xf156; fa-rupee',
            'fa-safari' => '&#xf267; fa-safari',
            'fa-sliders' => '&#xf1de; fa-sliders',
            'fa-slideshare' => '&#xf1e7; fa-slideshare',
            'fa-smile-o' => '&#xf118; fa-smile-o',
            'fa-sort-asc' => '&#xf0de; fa-sort-asc',
            'fa-sort-desc' => '&#xf0dd; fa-sort-desc',
            'fa-sort-down' => '&#xf0dd; fa-sort-down',
            'fa-spinner' => '&#xf110; fa-spinner',
            'fa-spoon' => '&#xf1b1; fa-spoon',
            'fa-spotify' => '&#xf1bc; fa-spotify',
            'fa-square' => '&#xf0c8; fa-square',
            'fa-square-o' => '&#xf096; fa-square-o',
            'fa-star' => '&#xf005; fa-star',
            'fa-star-half' => '&#xf089; fa-star-half',
            'fa-stop' => '&#xf04d; fa-stop',
            'fa-subscript' => '&#xf12c; fa-subscript',
            'fa-tablet' => '&#xf10a; fa-tablet',
            'fa-tachometer' => '&#xf0e4; fa-tachometer',
            'fa-tag' => '&#xf02b; fa-tag',
            'fa-tags' => '&#xf02c; fa-tags',
        ];
    }
}
